language: node_js
cache: yarn
jobs:
  include:
    - stage: 'Linting'
      script: yarn lint
    - stage: 'Testing'
      name: Unit tests'
      script: yarn test
      name: 'UI tests'
      script: yarn test:ui
