name: Outdated dependencies

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  outdated:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '14'        
    - name: Run outdated dependecy check
      run: yarn outdated
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
