# This is a basic workflow to help you get started with Actions

name: Outdated dependencies

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  outdated:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
      with:
        node-version: '14'
        
        # Runs a single command using the runners shell
        - name: Run outdated dependecy check
          run: yarn outdated
          env:
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
